### ISSUE TITLE
Proto#1 5 messages en dur (Go | Nogo)

### ISSUE THREAD

**Issue by hugolepetit** [women-on-rails/safe_twitts#1]
Seed sur 5 messages au pif (db/seeds.rb)
Les prendre pour les afficher et les trier (Go ou Nogo)
L'application garde en mémoire le filtrage. Bouton pour toggle le filtrage.
On le fait en TDD

**Comment by celine-m-s** [comment]
Je viens de créer une PR => #3 
:)

**Comment by hugolepetit** [comment]
Il ne manque plus que le filtrage par message pour valider l'issue !

**Comment by celine-m-s** [comment]
On peut maintenant dire si un message est safe ou pas ! Je pense qu'on est bons pour cette issue, qu'en penses-tu ? 
=> #6
